/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'areaOptions' : Array<string>,
  'teamOptions' : Array<string>,
  'labels' : Array<[string, string]>,
  'logoUrl' : string,
  'bannerUrl' : string,
  'typeOptions' : Array<string>,
}
export interface Entry {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'entryType' : string,
  'area' : string,
  'createdAt' : bigint,
  'team' : string,
  'description' : string,
  'updatedAt' : bigint,
  'notes' : string,
}
export interface Stats {
  'howToCount' : bigint,
  'featureCount' : bigint,
  'issueCount' : bigint,
  'bugFixCount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntries' : ActorMethod<[], Array<Entry>>,
  'getEntriesByArea' : ActorMethod<[string], Array<Entry>>,
  'getEntriesByTeam' : ActorMethod<[string], Array<Entry>>,
  'getEntriesByType' : ActorMethod<[string], Array<Entry>>,
  'getEntry' : ActorMethod<[bigint], Entry>,
  'getSettings' : ActorMethod<[], AppSettings>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEntry' : ActorMethod<
    [bigint, string, string, string, string, string, string, string],
    Entry
  >,
  'updateSettings' : ActorMethod<[AppSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];