/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'entryType' : IDL.Text,
  'area' : IDL.Text,
  'createdAt' : IDL.Int,
  'team' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'areaOptions' : IDL.Vec(IDL.Text),
  'teamOptions' : IDL.Vec(IDL.Text),
  'labels' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'logoUrl' : IDL.Text,
  'bannerUrl' : IDL.Text,
  'typeOptions' : IDL.Vec(IDL.Text),
});
export const Stats = IDL.Record({
  'howToCount' : IDL.Nat,
  'featureCount' : IDL.Nat,
  'issueCount' : IDL.Nat,
  'bugFixCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getEntriesByArea' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
  'getEntriesByTeam' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
  'getEntriesByType' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
  'getEntry' : IDL.Func([IDL.Nat], [Entry], ['query']),
  'getSettings' : IDL.Func([], [AppSettings], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Entry],
      [],
    ),
  'updateSettings' : IDL.Func([AppSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'entryType' : IDL.Text,
    'area' : IDL.Text,
    'createdAt' : IDL.Int,
    'team' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'areaOptions' : IDL.Vec(IDL.Text),
    'teamOptions' : IDL.Vec(IDL.Text),
    'labels' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'logoUrl' : IDL.Text,
    'bannerUrl' : IDL.Text,
    'typeOptions' : IDL.Vec(IDL.Text),
  });
  const Stats = IDL.Record({
    'howToCount' : IDL.Nat,
    'featureCount' : IDL.Nat,
    'issueCount' : IDL.Nat,
    'bugFixCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getEntriesByArea' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
    'getEntriesByTeam' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
    'getEntriesByType' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
    'getEntry' : IDL.Func([IDL.Nat], [Entry], ['query']),
    'getSettings' : IDL.Func([], [AppSettings], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Entry],
        [],
      ),
    'updateSettings' : IDL.Func([AppSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };